import type { DesignStyle } from './types';

export const DESIGN_STYLES: DesignStyle[] = [
  { id: 'mid-century-modern', name: 'Moderní styl 50. let', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost ve stylu moderny 50. let. Použijte čisté linie, organické křivky a přírodní materiály jako dřevo. Zahrňte ikonické kusy nábytku.' },
  { id: 'scandinavian', name: 'Skandinávský', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost ve skandinávském stylu se zaměřením na minimalismus, jednoduchost a funkčnost. Použijte světlou paletu barev s přírodními dřevěnými akcenty a útulnými textiliemi.' },
  { id: 'bohemian', name: 'Bohemian', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost v bohémském stylu. Použijte různé textury, vzory a barvy. Zahrňte rostliny, vintage nábytek a předměty z cest po světě.' },
  { id: 'industrial', name: 'Industriální', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost v industriálním stylu s odhalenými surovými materiály jako cihla, kov a beton. Vytvořte otevřené prostory, neutrální tóny a utilitární objekty.' },
  { id: 'coastal', name: 'Pobřežní', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost v pobřežním stylu (Hamptons). Použijte světlou a vzdušnou paletu barev s modrou a bílou, přírodní materiály jako dřevo a ratan a hodně přirozeného světla.' },
  { id: 'minimalist', name: 'Minimalistický', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost v minimalistickém stylu. Udržujte ji jednoduchou, přehlednou a monochromatickou. Každý objekt by měl být funkční nebo krásný.' },
  { id: 'japandi', name: 'Japandi', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost ve stylu Japandi, který kombinuje japonský minimalismus se skandinávskou funkčností. Použijte neutrální barvy, přírodní materiály a čisté linie k vytvoření klidného a vyrovnaného prostoru.' },
  { id: 'art-deco', name: 'Art Deco', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost ve stylu Art Deco s důrazem na půvab, luxus a řád s odvážnými geometrickými vzory, sytými barvami a kovovými povrchy.' },
  { id: 'farmhouse', name: 'Farmářský', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost v moderním farmářském stylu. Zkombinujte rustikální kouzlo s moderním komfortem za použití recyklovaného dřeva, neutrálních barev a útulných textilií.' },
  { id: 'transitional', name: 'Přechodný', prompt: 'DŮLEŽITÉ: Pečlivě zachovejte původní rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Na tomto základě redesignujte místnost v přechodném stylu, který je směsí tradičního a moderního. Použijte neutrální paletu barev k vytvoření čisté a klidné atmosféry.' },
];