import { GoogleGenAI, Modality } from "@google/genai";

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
const model = 'gemini-2.5-flash-image';

async function generateImageFromPrompt(base64Image: string, mimeType: string, prompt: string): Promise<string> {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const generatedBase64 = part.inlineData.data;
        const generatedMimeType = part.inlineData.mimeType;
        return `data:${generatedMimeType};base64,${generatedBase64}`;
      }
    }

    throw new Error("No image was generated by the API.");
}

export const redesignImage = async (
    base64Image: string, 
    mimeType: string, 
    stylePrompt: string
): Promise<string> => {
  return generateImageFromPrompt(base64Image, mimeType, stylePrompt);
};

export const refineImageWithChat = async (
    base64Image: string, 
    mimeType: string, 
    chatPrompt: string
): Promise<string> => {
    const fullPrompt = `Na základě požadavku uživatele upravte tento obrázek. Uživatel si přeje: "${chatPrompt}". DŮLEŽITÉ: Tuto změnu proveďte při zachování původního rozložení místnosti, včetně všech dveří, oken a architektonických prvků. Změna by měla být realistická a hladce zapadnout do stávající struktury.`;
    return generateImageFromPrompt(base64Image, mimeType, fullPrompt);
};